# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Learn Cpp
email: phatnguyen240899@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog hướng dẫn Cpp viết bởi Admin TuiTuCode
  
  
baseurl: "/cpp" # the subpath of your site, e.g. /blog
url: "http://phatnguyendev.github.io" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer

built-by: Phat Nguyen

copyright:
   name: Phat Nguyen
   link: 'http://phatnguyendev.github.io'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-143351073-1

# Comments
disqus: yes
disqus-shortname: webjeda-demo

#social
facebook: http://facebook.com/Senlucifer
github: http://github.com/akasukipq
email: phatnguyen240899@gmail.com

#facebook like box
fb-like-box: no
#fb-app-id: 549480635219583
#fb-page-url: https://www.facebook.com/webjeda/
#fb-page-title: webjeda

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag]

